### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by pchalamchala** [HCL-TECH-SOFTWARE/dxsync#7]
@ThomasHurek - Can you please check this ? Below are my OS, Node and NPM versions

macOS Catalina 10.15.6
Node v12.18.3
NPM 6.14.6

---

$ dxsync init
evalmachine.<anonymous>:36
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:36:5
    at Object.<anonymous> (/usr/local/lib/node_modules/dxsync/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dxsync/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)

**Comment by ThomasHurek** [comment]
@pchalamchala Which steps did you take to install the tool? Did you download the release package and run the install command or just used npm install?

**Comment by ThomasHurek** [comment]
Have not heard back so will close this issue. Please reopen as needed.
